spring.datasource.url=jdbc:mysql://localhost:3306/military_assets?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Jagadeesh@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
